### ISSUE TITLE
possible to capture just the video without the AR overlay?

### ISSUE THREAD

**Issue by shi-yan** [AFathi/ARVideoKit#102]
If I want to only capture the video stream without the AR overlay, can I do it?

I want to use AR to guide video recording, but I don't want to record the AR overlay.

Thanks!

**Comment by digitallysavvy** [comment]
@shi-yan you can get that directly from ARKit using [ARFrame's capturedImage](https://developer.apple.com/documentation/arkit/arframe/2867984-capturedimage)

**Comment by AFathi** [comment]
@shi-yan see the following instructions,

@digitallysavvy that's a good point. In addition to the option to retrieve the original frame using the `ARFrame.capturedImage`, you can also use ARVideoKit's [`RenderARDelegate`](https://github.com/AFathi/ARVideoKit/wiki/RenderARDelegate). To set the the `RenderARDelegate`, make sure to follow these steps:

1. Set `renderAR` of [`RecordAR`](https://github.com/AFathi/ARVideoKit/wiki/RecordAR#var-renderarrenderardelegate) to a class conforming to `RenderARDelegate`.

```
recordAR?. renderAR = self
```

2. Make sure the class conforming to `RenderARDelegate` has the required method
```
class MyViewController: UIViewController, RenderARDelegate {
...
...
...
func frame(didRender buffer: CVPixelBuffer, with time: CMTime, using rawBuffer: CVPixelBuffer) {
// Use `rawBuffer` here to retrieve the original frame
// Use `buffer` to retrieve the rendered frame
}
  
}
```

**Comment by shi-yan** [comment]
Thank you. I'm aware of capturedImage. The reason for raising the question was that if I use capturedImage, I need to implement my own video encoding code?

@AFathi Thank you very much for the answer!

**Comment by taeger** [comment]
@AFathi: Sorry, bloody beginner's question. What do I have to write – HERE – to make this work?

`func frame(didRender buffer: CVPixelBuffer, with time: CMTime, using rawBuffer: CVPixelBuffer) {
– HERE –
}
  `
