### ISSUE TITLE
Record always show black video only

### ISSUE THREAD

**Issue by parth0072** [AFathi/ARVideoKit#11]
Hey
I have used ARVideoKit for recording in my AR applications. but when I start recording and I have recorded video for 10 sec but it only show me black screen only. also show black screen in photo too.

**Comment by AFathi** [comment]
Hey @parth0072,
Can you please specify how you implemented `ARVideoKit` into your project?

-Ahmed

**Comment by parth0072** [comment]
Thanks for reply.
yesterday i had solved that problem .
due to some mistake in my logic that's why it was not worked
