### ISSUE TITLE
Cannot record custom video sizes

### ISSUE THREAD

**Issue by davidxiasc** [AFathi/ARVideoKit#14]
I wish to record videos with custom sizes, but under the current implementation, the only options appear to landscape and portrait

**Comment by AFathi** [comment]
@davidxiasc,
Can you please clarify what do you mean by custom size?

-Ahmed

**Comment by davidxiasc** [comment]
For example, say my SCNView is a square, the view that is output always appears to have a specific aspect ratio (stretched). However, what I actually want is just the square video

**Comment by AFathi** [comment]
@davidxiasc,
Thank you for the feedback, I'll consider this in future updates!

However, for now, you may resize the video asset after recording. Because `ARVideoKit` currently renders the AR scene based on the raw frame size.

-Ahmed

**Comment by seawolf86** [comment]
@AFathi How can i setup my video to be 16:9? Also some property for resolution?

**Comment by GiacomoLeopizzi** [comment]
Hey guys, I solved as I explained here. I hope it can help!

https://github.com/AFathi/ARVideoKit/issues/43#issuecomment-583324809

**Comment by GiacomoLeopizzi** [comment]
@davidxiasc, @LeonardRockstar, @seawolf86  the issue is solved in current version of the library.
Use:
```
recorder.contentMode = .viewAspectRatio
```
To record with same aspect ratio of the view you used to create the RecordAR instance.

Regards,
Giacomo
