### ISSUE TITLE
Video Recorded Doesn't Show ARKit Shadows

### ISSUE THREAD

**Issue by masonvscode** [AFathi/ARVideoKit#16]
Recording appears without shadows
![img_5420](https://user-images.githubusercontent.com/9758594/34233643-78b97b1a-e59b-11e7-941e-4a7eebc26213.PNG)
Expected result includes shadows on the shape
![img_5418](https://user-images.githubusercontent.com/9758594/34233644-78cf543a-e59b-11e7-9c4e-e0d798ab4fd9.PNG)

**Comment by AFathi** [comment]
@masonvscode,
How are you creating the material of the paint?

-Ahmed

**Comment by huntermonk** [comment]
We are just using automatic lighting from `ARKit`. So just:
```
sceneView.automaticallyUpdatesLighting = true
```

**Comment by AFathi** [comment]
@huntermonk,
What are you using to create the AR paint material? Can you share the code for that?

**Comment by huntermonk** [comment]
Yep. The example above is colored, but for simplification, the same effect applies when just using a `SCNNode` with no changes to diffuse.

```
static var whiteBall: SCNNode {
    return SCNNode(geometry: SCNSphere(radius: 0.005))
}
```

**Comment by AFathi** [comment]
@huntermonk,
I'll try to reproduce the issue and get back to you soon :)

-Ahmed

**Comment by huntermonk** [comment]
Great!

**Comment by huntermonk** [comment]
Thanks @pionl, that is really interesting. Is that lighting baked in, or does that allow for dynamic lighting?

Our nodes are moving, so dynamic shadows are important for us.

**Comment by pionl** [comment]
@huntermonk I use all default values - dynamic lighting automatically managed by the SceneKit. There is probably problem how SceneKit adds the light into the scene. If I manually add light to rootNode of the scene by calling `sceneView.scene.rootNode.addChildNode(lightNode)`, then all works fine (lighting is applied to all models).

**Comment by miliPolo** [comment]
I I read the source code and found that I needed to set the parameters of the Render.
In the function func doRender(scene: SCNScene, withOptions options: VideoRendererOptions, until: @escaping () -> (Bool), andThen: @escaping (_: URL) -> ())
Like this
Let renderer = SCNRenderer(device: nil, options: nil)
The renderer. Scene = scene
The renderer. AutoenablesDefaultLighting = true
It works！

**Comment by miliPolo** [comment]
@huntermonk @AFathi 
I read the source code and found that I needed to set the parameters of the Render.
In the function func doRender(scene: SCNScene, withOptions options: VideoRendererOptions, until: @Escaping () -> (Bool), andThen: @Escaping (_: URL) -> ())
Like this
Let renderer = SCNRenderer(device: nil, options: nil)
The renderer. Scene = scene
The renderer. AutoenablesDefaultLighting = true

It works！

**Comment by huntermonk** [comment]
@miliPolo nice! Are you planning on submitting a PR?

**Comment by miliPolo** [comment]
@huntermonk  Hi, I have commit the code

**Comment by AFathi** [comment]
@huntermonk, I just merged @miliPolo 's commit to the master branch!
