### ISSUE TITLE
Any plans to support Objective-C?

### ISSUE THREAD

**Issue by adarsh431** [AFathi/ARVideoKit#17]
Hi,

Thanks for the awesome work. Recently I started using ARKit and ARVideoKit and because of the usage of Swift, my app got bloated up in size. So I'd like to implement ARKit on Objective-C, and would like to know if you have any plans on supporting ARVideoKit in it?

Thanks.

**Comment by AFathi** [comment]
@adarsh431,

Yes, I'm open-sourcing **ARVideoKit** this month and it will support Objective-C and include other new features and fixes!

-Ahmed

**Comment by adarsh431** [comment]
@AFathi 
Thanks a lot.

**Comment by yderidde** [comment]
hey @adarsh431 ! Amazing work you did here !
Looking forward to use this in my ObjC project... do you have a timeframe for when you are gonna open source it ? (more precise than just 'this month') ?

**Comment by AFathi** [comment]
@yderidde,

Yes! The open source version will be up this week and I will include an example Objective-C project.

**Comment by yderidde** [comment]
@AFathi you're the best !

**Comment by yderidde** [comment]
@AFathi I like your 'fake' counter haha

**Comment by AFathi** [comment]
@yderidde @adarsh431 : 
Check out the latest commit!
