### ISSUE TITLE
Crash when record and stop video immediately

### ISSUE THREAD

**Issue by kuajia** [AFathi/ARVideoKit#24]
This is my first time in managing a video in a SCNView. I started using your library, and I solved a lot of problems, but  I am still having an issue when starting and immediately stopping the video: I also noticed that your swift example project is having the same crash, with this log : 

2018-02-07 14:25:23.808628+0100 ARVideoKit-Example[3957:1450433] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles

2018-02-07 14:25:23.808945+0100 ARVideoKit-Example[3957:1450433] [MC] Reading from public effective user settings.

2018-02-07 14:25:25.226704+0100 ARVideoKit-Example[3957:1450312] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[AVAssetWriter finishWritingWithCompletionHandler:] Cannot call method when status is 0'

*** First throw call stack:

(0x18131b164 0x180564528 0x186c2ad68 0x104df119c 0x104e0f3f0 0x104de4934 0x105a852cc 0x105a8528c 0x105a89ea0 0x1812c3344 0x1812c0f20 0x1811e0c58 0x18308cf84 0x18a9395c4 0x1045a1100 0x180d0056c)

libc++abi.dylib: terminating with uncaught exception of type NSException

It seems like there is an unknown status (value 0)  on the assetsWriter.status.rawValue: I can avoid the error, using a check, when this value is 0, but next time you will run the record; the application won't do it.

**Comment by AFathi** [comment]
@kuajia,
Do you mind sharing what device were you testing on?

**Comment by kuajia** [comment]
Sorry, I forgot it... I used an iPhone X

**Comment by AFathi** [comment]
@kuajia,
There are 2 different ways to temporarily fix this issue:

1. Add a minimum of **1 second** before allowing the user to stop the video recorder.

2. If you're using the open-sourced version of  **ARVideoKit**, you may go to the `ARVideoKit/Rendering/Writer/WritAR.swift` file and replace the function `end(writing )` with the following block of code:

```
    func end(writing finished: @escaping () -> Void){
        if let session = session {
            if session.isRunning {
                session.stopRunning()
            }
        }
        
        if assetWriter.status == .writing {
            assetWriter.finishWriting(completionHandler: finished)
        }
    }
```

**Comment by AFathi** [comment]
Fix for the issue has been included in v. 1.3
