### ISSUE TITLE
ARVideoKit Module compiled with Swift 4.0.2 cannot be imported in Swift 4.0

### ISSUE THREAD

**Issue by DrashtiBhuta** [AFathi/ARVideoKit#3]

**Comment by AFathi** [comment]
Can you please specify how you include the framework into your project?

**Comment by CoderTian** [comment]
me too， how to resolve this?

**Comment by AFathi** [comment]
@CoderTian, do you mind specifying how you're including `ARVideoKit.framework` into your project?

Would appreciate detailed explanations of the the issue to help me resolve it!

-Ahmed
