### ISSUE TITLE
Unable to Archive due to Bitcode

### ISSUE THREAD

**Issue by allenwixted** [AFathi/ARVideoKit#39]
I have been getting this error over the last week and am unable to resolve it. Apologies if this is incorrect usage of the "issues" tab. 

`Auto-Linking bitcode bundle could not be generated because '/Users/allenwixted/Desktop/iOS : OS X/NoPlaceLike/Frameworks/ARVideoKit.framework/ARVideoKit' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build`

I've tried [this article](https://medium.com/@heitorburger/static-libraries-frameworks-and-bitcode-6d8f784478a9) and it worked for a day or so. Then I realised I was working on Xcode beta and needed to build it for iOS 11.3 and am unable to resolve the issue this time around. Any help is much appreciated.

**Comment by AFathi** [comment]
@allenwixted, are you using the `.framework` binary file?

If so, I'd recommend to follow those steps:
> https://github.com/AFathi/ARVideoKit#publishing-to-the-app-store

**Comment by allenwixted** [comment]
Hi @AFathi I couldnt get it to work so I just removed the framework and went with importing the code folder itself. Thanks for responding though. Side Q regarding licencing, my app doesn't have a licence page yet (it's just a basic table view with ARViews spanning from those). Is it okay to mention/link ARVideoKit in the AppStore page or is there a specific requirement in what way to give you the credit deserved for the framework?
