### ISSUE TITLE
Stretching on iPhone X

### ISSUE THREAD

**Issue by yeldarby** [AFathi/ARVideoKit#4]
The underlying image and the `SceneKit` content are misaligned on the iPhone X (I presume because of the different aspect ratio of the display). It looks like the `SceneKit` content is rendered too wide relative to the camera image.

Here's an example. First is a screenshot of what it looks like in the app. Second is an image exported from `ARVideoKit` (videos have the same issue; was just easier to demonstrate with a photo):

![img_0163](https://user-images.githubusercontent.com/870796/32969734-d345613e-cbab-11e7-83f0-eb84654fd098.PNG)
![img_0162](https://user-images.githubusercontent.com/870796/32969737-d5614320-cbab-11e7-8ac5-b81935c50721.JPG)

**Comment by AFathi** [comment]
Hey @yeldarby!
Thank you for creating this issue. Can you capture and send photos from different face angles or poses?

Because I'm assuming the problem may be caused from the renderer.

By different angles or poses I mean something like that:
![rnnface](https://user-images.githubusercontent.com/4106695/32970026-4b7d5126-cbb5-11e7-9f91-74c4c2d58c08.jpg)

-Ahmed

**Comment by yeldarby** [comment]
Sure, how's this?

ARVideoKit: https://www.dropbox.com/s/ckkuqbnj1gqm881/ARVideoKit.MP4?dl=0
iOS Video Recording: https://www.dropbox.com/s/6qxjiqu77gl76tb/iOS-Video-Recording.MOV?dl=0

**Comment by AFathi** [comment]
That's good enough! I believe I know where the issue is coming from and I'll publish an update with a new option in [`RecordAR`](https://github.com/AFathi/ARVideoKit/wiki/RecordAR) to configure the renderer by tomorrow.

I'll inform you in this thread when the update is ready.

-Ahmed

**Comment by yeldarby** [comment]
Awesome!!

**Comment by AFathi** [comment]
Hey @yeldarby!
Check out v. 1.12 of [ARVideoKit](https://github.com/AFathi/ARVideoKit/releases/tag/1.12)!

**Comment by yeldarby** [comment]
Excellent. Do you have Paypal? This framework is going to save me a ton of time!

**Comment by AFathi** [comment]
@yeldarby, I'm really glad my [framework](https://github.com/AFathi/ARVideoKit) is helping you and many others ☺️. I really appreciate your feedback!

My PayPal email is: ahmedfbekhit@gmail.com

-Ahmed
