### ISSUE TITLE
Audio configuration has wrong setup

### ISSUE THREAD

**Issue by AgapovOne** [AFathi/ARVideoKit#41]
I want to disable audio for AR in my project. (Apple declined an app because I don't use a microphone at all for my application, but do require a permit)

When I set `requestMicPermission` or `enableAudio` after RecordAR initialization, it does setup() in viewDidLoad(). That's too early because it would request mic permission even if I don't want to use it.

We can add read-only configuration object and pass it into `RecordAR` object on initialization step like `@objc override public init?(ARSceneKit: ARSCNView, configuration: RecordARConfiguration)`. the setup would respect the configuration object and won't use default values every time on initialization.

What do you think? I wanted to make it as a struct with `let prop`, but that way I would disable @objc compatibility.

```swift
struct RecordARConfiguration {
    let enableAudio: Bool = true
}
```

Currently, I did open RecordAR for subclassing and did override `enableAudio` and `requestMicPermission` properties. Then I used my subclass as a RecordAR view.

```swift
class DefaultRecordAR: RecordAR {
    private var isEnableAudio: Bool = false
    override var enableAudio: Bool {
        get {
            return isEnableAudio
        }
        set {
            isEnableAudio = newValue
        }
    }
}
```

So:
Quick hotfix: make RecordAR open for subclassing, make configuration variables open for subclassing too
Proper fix: add configuration object to inject into `RecordAR` and setup it properly.

**Comment by AFathi** [comment]
@AgapovOne, check out latest commit: https://github.com/AFathi/ARVideoKit/tree/f79760470edb37e64381042cd80152c16b71832b
