### ISSUE TITLE
Square Video Recording

### ISSUE THREAD

**Issue by kellum42** [AFathi/ARVideoKit#43]
Are you able to make the video a square? So the output of the recording is a movie file with a 1x1 aspect ratio?

**Comment by GiacomoLeopizzi** [comment]
Hi! I had the same issue and I think I have a solution to propose.

I added a new ARFrameMode

```
@objc public enum ARFrameMode: Int {
    case auto    
    case aspectFit
    /// Recommended for iPhone X
    case aspectFill
    
    case viewAspectRatio
} 
```
And added this code to the bufferSize var in RenderArR.swift (line 40)

```
case .viewAspectRatio where view is UIView:
                let bufferWidth = CVPixelBufferGetWidth(raw)
                let bufferHeight = CVPixelBufferGetHeight(raw)
                let viewSize = (view as! UIView).bounds.size
                let targetSize = AVMakeRect(aspectRatio: viewSize, insideRect: CGRect(x: 0, y: 0, width: bufferWidth, height: bufferHeight)).size
                width = Int(targetSize.width)
                height = Int(targetSize.height)
```
In order to use AVMakeRect I imported AVFoundation in the same file. 

@AFathi please let me know what you think about my solution. I think that in this way it's easy to support custom sizes of the recording cause the size is calculated based on the aspect ratio of the view.

Regards,
Giacomo Leopizzi

**Comment by AFathi** [comment]
@GiacomoLeopizzi, great approach! Can you create a pull request with these changes?

Also the only thing I'd change is this the force wrapping part.
from this:
```
                let viewSize = (view as! UIView).bounds.size
```

to this:

```
                let viewSize = (view as? UIView)?.bounds.size ?? .zero
```

or have some kind of a guard statement.

**Comment by GiacomoLeopizzi** [comment]
@AFathi sure! I’ll do it today. 
About the guard, I forced the cast cause I put a where in the case switch. If you think it’s not fine, I can add a guard of course!

**Comment by GiacomoLeopizzi** [comment]
@kellum42 the issue is solved in current version of the library. 
Use:
```
recorder.contentMode = .viewAspectRatio
```
To record with same aspect ratio of the view you used to create the RecordAR instance.

Regards,
Giacomo

**Comment by J-Arji** [comment]
hey, I can't found  "viewAspectRatio" in contentMode .
can you help me?
how can  able to make the video a square ?
thanks

**Comment by GiacomoLeopizzi** [comment]
Sure @J-Arji

**Comment by GiacomoLeopizzi** [comment]
Sure @J-Arji 
You should have something like
```
let view = ARSCNView()
// Add subview, setup constraints, etc
guard let recorder = RecordAR(ARSceneKit: view) else {         
    // do something...
}
recorder.contentMode = .viewAspectRatio
```

If you cannot find it please check you have the latest version of the library

**Comment by GiacomoLeopizzi** [comment]
In contentMode `.viewAspectRatio` the output video has the same aspect ratio of the view, so just make sure the view has 1:1 aspect ration and the output will have square frames.

**Comment by J-Arji** [comment]
i add this line 
```
guard let recorder = RecordAR(ARSceneKit: sceneView) else {
            print("can not add recorder ")
            return
        }
        if ratioMode == .normal {
            recorder.contentMode = . viewAspectRatio
        } else if ratioMode == .story {
            recorder.contentMode = .aspectFill
            
        } else {
            recorder.contentMode = .auto
            
        }
```

but when I play record video it's fill

**Comment by GiacomoLeopizzi** [comment]
You should set the recorder.contentMode to `.viewAspectRatio` in order to get the output you want.

**Comment by GiacomoLeopizzi** [comment]
Of course the view itself has also to be 1:1

**Comment by J-Arji** [comment]
when I played with it with a custom view (1:1)
<img width="387" alt="Screen Shot 2020-04-23 at 7 30 43 PM" src="https://user-images.githubusercontent.com/11584951/80114540-f3cc5800-8598-11ea-8dc5-14a593b72db2.png">

and when i payed with defult player ios (AVPlayerViewController)
![0dcc28a2-5b30-45cc-b340-7c42e830739c](https://user-images.githubusercontent.com/11584951/80114245-989a6580-8598-11ea-9cd2-beef4870e191.JPG)

**Comment by GiacomoLeopizzi** [comment]
This should happen cause contentMode is not to `.viewAspectRatio`

**Comment by J-Arji** [comment]
but content mode is to `.viewAspectRatio`

I change it

**Comment by GiacomoLeopizzi** [comment]
Are you sure it's called? Cause I noticed you have an if block, maybe ratioMode is not `.normal`

**Comment by J-Arji** [comment]
Yeah, I sure 
I want the video output to be square
but  the video output  is 👇🏻
<img width="448" alt="Screen Shot 2020-04-24 at 1 24 00 PM" src="https://user-images.githubusercontent.com/11584951/80193927-dd70db80-862e-11ea-9971-d353cc9dedfb.png">

**Comment by J-Arji** [comment]
when I breakpoint buffer size in write  return 
![PHOTO-2020-04-24-13-34-58](https://user-images.githubusercontent.com/11584951/80195466-1ca02c00-8631-11ea-84ab-cc901009eaa9.jpg)

but in RanderAr buffersize is 1080,1080 

when I call again width and height it's ok 
why ??

**Comment by GiacomoLeopizzi** [comment]
When you call again you mean on next frame or next recording (I mean you stop recording and start it again)?

**Comment by J-Arji** [comment]
yeah,
I understand why I have a problem.
I set  ```recorder?.onlyRenderWhileRecording = false```
when I start and stop is ok 
I change  ```onlyRenderWhileRecording``` to true and it's ok 

but I think this part has a problem.
