### ISSUE TITLE
'RecordARDelegate' is unavailable: cannot find Swift declaration for this protocol

### ISSUE THREAD

**Issue by Cez95** [AFathi/ARVideoKit#47]
I followed the first setup instructions and when I did so it ran fine on my physical device, however, its not able to complile on the simulators. How can I work around this problem as I still need to test other aspects of my app on the simulator. Thanks

**Comment by AFathi** [comment]
@Cez95 can you clarify what error you're receiving when you run your application on a simulator?

**Comment by Cez95** [comment]
Yea, the error I get is 'RecordARDelegate' is unavailable: cannot find Swift declaration for this protocol. Its a runtime error and when I run the app on my physical device it disapears. Only shows when I have a simulator as the deployent target

**Comment by Cez95** [comment]
Unfortunately, none of these solutions work. The problem continues to persist for simulators. Will there be a cocoa pod for this project available in the future?

**Comment by AFathi** [comment]
@Cez95, yes I'm currently working on it under the [`pkg-manager`](https://github.com/AFathi/ARVideoKit/tree/pkg-manager) branch.

However, in the mean time I'd recommend installing the framework by dragging the `ARVideoKit.xcodeproj` into your project.

**Comment by AFathi** [comment]
@Cez95, you can now install **ARVideoKit** using Cocoapods by doing the following:

1. add this line to your `Podfile`:
```
pod 'ARVideoKit', :git => 'https://github.com/AFathi/ARVideoKit.git'
```
2. then install
``` 
$ pod install
```

**Comment by Cez95** [comment]
This is perfect! I was still having issues with inserting the framework but this changes the game! Thank you!
