### ISSUE TITLE
Logo proposal for ARVideoKit

### ISSUE THREAD

**Issue by ggabogarcia** [AFathi/ARVideoKit#54]
Hello, I'm a graphic designer and I like to collaborate with open source projects. I would like to design a logo for your Project I will be happy to collaborate with you :)

**Comment by AFathi** [comment]
Hi @ggabogarcia, 

Absolutely, feel free to design the logo and attach it to a comment here or update the `README.md`  file and create a pull request!

**Comment by AFathi** [comment]
@ggabogarcia, I will also add your name (and portfolio) in a credits section in the repository!

**Comment by ggabogarcia** [comment]
I will start to make some sketches :)

**Comment by AFathi** [comment]
Awesome, looking forward to seeing it!

**Comment by ggabogarcia** [comment]
Hello sir, here is my proposal, I hope you like it :) The idea is simple but with great impact. :) Any suggestions let me know :)

![arvideokit](https://user-images.githubusercontent.com/35750428/42539470-cf54ce20-8460-11e8-89c6-d41f3fd36ff4.jpg)

**Comment by AFathi** [comment]
@ggabogarcia, looking good! I only have a comment about that misaligned line, not sure if it's on purpose or a mistake but I'd try to make it a straight line :)
<img width="58" alt="screen shot 2018-07-10 at 10 40 24 pm" src="https://user-images.githubusercontent.com/4106695/42547886-54bcf8c2-8492-11e8-9c06-33d6b3e5300e.png">
<img width="52" alt="screen shot 2018-07-10 at 10 40 19 pm" src="https://user-images.githubusercontent.com/4106695/42547887-54ce7ed0-8492-11e8-8b7e-b3b6a37216b6.png">
<img width="237" alt="screen shot 2018-07-10 at 10 40 11 pm" src="https://user-images.githubusercontent.com/4106695/42547888-54e0b370-8492-11e8-9030-9a1d71e2574b.png">

**Comment by ggabogarcia** [comment]
Do not worry, that's just a draft :)

**Comment by AFathi** [comment]
@ggabogarcia, sounds good! it looks great so far!

**Comment by ggabogarcia** [comment]
I would like to know if you like it, or do you want to make some changes? otherwise, I will do the final art and send you all editable files, EPS, SVG and PDF :)

**Comment by ggabogarcia** [comment]
@AFathi Maybe you were thinking about something else? :)

**Comment by AFathi** [comment]
@ggabogarcia, the only change I'd suggest is maybe changing the colors a little bit. I'd try red instead of orange, lighter purple, and off or darker blue.

**Comment by AFathi** [comment]
take a look at the colors I'm using on my website's bio: http://www.ahmedbekhit.com
<img width="1226" alt="screen shot 2018-07-10 at 11 05 51 pm" src="https://user-images.githubusercontent.com/4106695/42548591-cf826eae-8495-11e8-8bfb-8ee36bf90e97.png">

**Comment by ggabogarcia** [comment]
I get it! I will make the change of colors :)

**Comment by ggabogarcia** [comment]
Hello, this is final art, on the left I used the colors of your website, on the right the colors that you suggested to me :) 

![arvideokit 1](https://user-images.githubusercontent.com/35750428/42587917-cbf33612-8501-11e8-851e-feeaf939600c.jpg)

**Comment by AFathi** [comment]
@ggabogarcia, both icons look beautiful 😍! Do you mind emailing me the editable files of both icons to: me@ahmedbekhit.com

**Comment by ggabogarcia** [comment]
Of course if :) let me prepare them, I'm glad you'll like them :smile:

**Comment by AFathi** [comment]
@ggabogarcia, let me know when you email the files to me 😊!

**Comment by ggabogarcia** [comment]
I'm on it :smile_cat:

**Comment by ggabogarcia** [comment]
Ready! Archives sended :)

**Comment by ggabogarcia** [comment]
![DERECHOS.jpg](https://cdn.steemitimages.com/DQmVSH7hxt3nuyDxNRdWUBUBtfR11TyvLxM1F1C4vYW5UzG/DERECHOS.jpg)
This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)

**Comment by ggabogarcia** [comment]
:thinking: Maybe I can do something

**Comment by AFathi** [comment]
Sure, fee free to try out what you’re thinking :)

**Comment by ggabogarcia** [comment]
Hello sir, this is the idea for the readme, I hope you like it :smile: . The photo of the corridor is blurred since I do not have the original file

![banner](https://user-images.githubusercontent.com/35750428/42696170-fee27fde-867c-11e8-8a5e-8b1e1fea4970.jpg)

**Comment by AFathi** [comment]
@ggabogarcia, looking good! I'd only change the footer color from green to black or off white (#f1f1f1)

**Comment by ggabogarcia** [comment]
![banner 2](https://user-images.githubusercontent.com/35750428/42716004-156749aa-86bf-11e8-9b35-cf4c4fd1fee9.jpg)

**Comment by AFathi** [comment]
@ggabogarcia, just added to the header to the repo's README file and added your work's license to the [License](https://github.com/AFathi/ARVideoKit#license) section :)

Please let me know if you'd like to edit or add something to the license section.

Thank you so much for your contribution to **ARVideoKit** 🙏😊
