### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by pingusNikalex** [AFathi/ARVideoKit#56]
How to use this libs for recording video in landscape and portrait application. If ARVideoKit always set device orientation in portrait mode?

**Comment by AFathi** [comment]
@pingusNikalex, **ARVideoKit** do support landscape and portrait recording. To properly setup your application for this use please add the following to your application's delegate file:

```
func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
return ViewAR.orientation
}
```

then customize the following properties:
```
        recorder?.inputViewOrientations = [.landscapeLeft, .landscapeRight, .portrait]
        // Insert the buttons/subviews you'd want to rotate in your UIViewController into the array
        recorder?.inputViewOrientationMode = .manual(subviews: [myBtn, myView, photoBtn])
```
Check the documentation of [`ARView`](https://github.com/AFathi/ARVideoKit/wiki/ARView) for more info.
