### ISSUE TITLE
ARFrameMode Compile Errors

### ISSUE THREAD

**Issue by gheatley** [AFathi/ARVideoKit#57]
Seems to be a little error with the latest commit. When I attempt to compile:

<img width="720" alt="screen shot 2018-07-17 at 09 36 36" src="https://user-images.githubusercontent.com/19663985/42806086-823f0444-89a5-11e8-8670-6867e49ed329.png">

**Comment by AFathi** [comment]
@gheatley, I believe you're using Xcode 10 beta. If so, I'll investigate the issue when the Xcode 10 stable release is out. Otherwise, please let me know what version of Xcode you're using?

**Comment by AFathi** [comment]
@gheatley, I just found where the issue is coming from, will push a new update in a few moments
