### ISSUE TITLE
Unable to find Framework for Swift 4.2

### ISSUE THREAD

**Issue by DanishRehma** [AFathi/ARVideoKit#61]
Hello, I am using Xcode 10 and Swift 4.2. I am unable to find compiled framework for Swift 4.2, I have tried Swift 4.2 branch but is contain the framework compiled for Swift 4.1.2. Please refer me where I could get latest framework. Thanks

**Comment by UninhibitedSoul** [comment]
You can see #44 issue

**Comment by UninhibitedSoul** [comment]
Same as #32.  LeonardRockstar commented on Apr 21

**Comment by DanishRehma** [comment]
Thank you, It is working now 👍
