### ISSUE TITLE
Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler: /myproject/ARVideoKit.framework/Modules/ARVideoKit.swiftmodule/arm64.swiftmodule

### ISSUE THREAD

**Issue by onlyonemuthuraj** [AFathi/ARVideoKit#66]
import ARVideoKit

Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler: /myproject/ARVideoKit.framework/Modules/ARVideoKit.swiftmodule/arm64.swiftmodule

Xcode version: 10

ARVideoKit version swift 4.2

**Comment by happythoughts247** [comment]
Yea, I'm getting the same error too.  Isn't this supposed to be the 4.2 build?  Maybe I downloaded the wrong one because the header says 4.1.2

**Comment by youllbejustfine** [comment]
You'll need to rebuild the Framework bundle for Swift 4.2. 

To do so, you'll need to use Carthage. Firstly, make sure it's installed on your computer. Then navigate to the ARVideoKit project folder in Terminal, and run the following command:

`carthage build --no-skip-current`

Then navigate to the ARVideoKit project folder and look in the Carthage/Build/iOS folder, and drag that ARVideoKit.framework into your embedded binaries.

An further note, after generating the framework in this way, I had to use this [StackOverflow answer ](https://stackoverflow.com/questions/30547283/submit-to-app-store-issues-unsupported-architecture-x86#answer-41416964) to strip away the simulator binaries.
