### ISSUE TITLE
How to add Gesture on AR objects 

### ISSUE THREAD

**Issue by Mitesh-Mewada** [AFathi/ARVideoKit#68]
Thank you for creating great useful library.
I am using this library and i want add **TapGesture** and **PinchGesture** on AR Object, how to add this, any one was done it? any idea how to i do that. 
Thanks.

**Comment by AFathi** [comment]
@Mitesh-Mewada, you may check the following [article](https://developer.apple.com/documentation/arkit/handling_3d_interaction_and_ui_controls_in_augmented_reality) by Apple to implement gestures to interact with AR objects.

https://developer.apple.com/documentation/arkit/handling_3d_interaction_and_ui_controls_in_augmented_reality
