### ISSUE TITLE
how to hide Monitoring detail 

### ISSUE THREAD

**Issue by Mitesh-Mewada** [AFathi/ARVideoKit#69]
I implement this lib. but when is run that time bottom side sow some detail(**Animations, Physics, Constraints, Particles, Delegate, Rendering, GPU and 2D**) how to hide or remove in my Application. 
Please help me.

**Comment by AFathi** [comment]
@Mitesh-Mewada, in order to hide these analysis you may use the following property in set it to `false`.

**SceneKit**
```
        sceneView.showsStatistics = false
```

**SpriteKit**
```
        SKSceneView.showsFPS = false
        SKSceneView.showsNodeCount = false
```
