### ISSUE TITLE
Module file's minimum deployment target is ios11.0

### ISSUE THREAD

**Issue by saikiran-magic** [AFathi/ARVideoKit#7]
Hello,

I need to have an optional feature which uses ARKit and ARVideoKit in my app, but don't want it to prevent users with iOS version less than 11.0 from downloading & using the rest of the app. Is there some way similar to weak link the ARVideoKit framework and put "@ available" checks as we do for every iOS framework? 

The error I get when trying to import in a project with deployment target 9.0 is 

`Module file's minimum deployment target is ios11.0 v11.0: <PROJECT_ROOT>/ARVideoKit.framework/Modules/ARVideoKit.swiftmodule/arm64.swiftmodule`

Thanks.

**Comment by AFathi** [comment]
Hey @saikiran-magic!
I'll be including a fix for this issue in v. 1.12 soon.

-Ahmed

**Comment by AFathi** [comment]
Hey @saikiran-magic!
Check out v. 1.12 of [ARVideoKit](https://github.com/AFathi/ARVideoKit/releases/tag/1.12)!

**Comment by saikiran-magic** [comment]
Awesome! Thanks @AFathi
