### ISSUE TITLE
Record SCNView?

### ISSUE THREAD

**Issue by davidvjc** [AFathi/ARVideoKit#76]
In the documentation you mention the ability to record a SCNView. How do I implement that?

The examples don't mention it and when I try using a SCNView instead of an ARSCNView or ARSKView I get errors all around. 

`recorder = RecordAR(ARSceneKit: sceneView)`

Does not seem to take SCNView as expected.

**Comment by AFathi** [comment]
Hi,

Please use this initializer instead:

`RecordAR(SceneKit: 'insert `SCNView` here')`

**Note** that if you installed `ARVideoKit` using the `.framework` file you won't be able to use the scene kit initializer because the binary file is not longer supported.

Regards,
Ahmed Bekhit

**Comment by davidvjc** [comment]
thanks!
